### ISSUE TITLE
2.6.1 set_list, get_list not working on 5.2

### ISSUE THREAD

**Issue by GDmac** [croxton/Stash#128]
When removing the set_list, the channel:entries does output entries. 
From template debugging it seems template_post_parse does return empty stuffs :-(
```
{exp:stash:set_list name="active_locations" parse_tags="yes" scope="site"}
   {exp:channel:entries channel="locaties" dynamic="off"}
	    {stash:locatie_naam}{title}{/stash:locatie_naam}
   {/exp:channel:entries}
{exp:stash:set_list}
```
```
(0.057837 / 7.06MB) -> Class Called: Channel
(0.060708 / 7.22MB) -> Method Called: entries
(0.107537 / 8.89MB) -> Data Returned
(0.107932 / 8.87MB) Calling Extension Class/Method: Stash_ext/template_post_parse
(0.108479 / 8.86MB) Returning No Results Content
(0.108536 / 8.86MB) -> Data Returned
```

**Comment by GDmac** [comment]
ps. this does work on my dev machine (php 5.4) but after upload to customer hosting (5.2) the list stays empty.

**Comment by croxton** [comment]
Stash isn't tested with 5.2 any longer, sorry - EE itself requires 5.3.10+. Can you upgrade the host? Running 5.2 in production is dangerous in any case.

**Comment by GDmac** [comment]
pffft - great - i'll see what i can do.
**Rock** (stuck) **hard place**

**Comment by GDmac** [comment]
FYI - the hoster moved the domain to another server (PHP 5.3.29) and stash works again.

**Comment by croxton** [comment]
Excellent!
