### ISSUE TITLE
Stash 2.6.2 / Mustash not cache breaking static files

### ISSUE THREAD

**Issue by richardschaefer** [croxton/Stash#130]
I'm sure this is related to the comments you've included for the last two version releases, but upgrading to 2.6.2 ignores cache breaking rules on Channel Entries publish/edit for static files. 2.6.0 works fine.

**Comment by croxton** [comment]
v2.6.1 fixed a bug where the entire static cache was cleared regardless of the cache-breaking rules that were matched. Therefore, even rules that did not match would cause the static cache to be cleared. It's likely your rules are incorrect and only seemed to be working because of the bug.

**Comment by richardschaefer** [comment]
Hi Mark, you're absolutely right. Was attempting to target static files by context only... #:my_context:static$# works a charm now, thx.
