### ISSUE TITLE
Caching a variable example not working

### ISSUE THREAD

**Issue by GDmac** [croxton/Stash#132]
I use the basic example from the docs, here
https://github.com/croxton/Stash/wiki/%7Bexp%3Astash%3Aset%7D#caching-a-variable

But, ***the variable never updates***. For testing purposes i have set ``refresh="2"``, 
But template debugging keeps reporting:
"*(0.036965 / 7.21MB) Stash: SET cached_more___entries to value ....*"

```
{exp:stash:set
    name="my_cached_blog_entries" 
    save="yes" 
    scope="site" 
    parse_tags="yes"
    replace="no" 
    refresh="60"
    output="yes"
}
    {exp:channel:entries channel="blog"}
        <p>{title}</p>
    {/exp:channel:entries}
{/exp:stash:set}
```

**Comment by GDmac** [comment]
Digging into it, inside set(), i tried adding:
```php
$this->_update = ($this->EE->localize->now > $this->EE->localize->now + ($refresh * 60));
```
However, (guestimating here), around line:485, the ``$existing_value`` is checked (var_dump confirms it's a string), and then ``$set`` is set to FALSE, so the whole ``if ($set) { ... }`` is skipped, and never updating.

**Comment by croxton** [comment]
It shouldn't update, it's cached! Variables must be *pruned* regularly from the cache so that they regenerate - the best way to do that is with a cron.
https://github.com/croxton/Stash/wiki/Cache-pruning-configuration

**Comment by croxton** [comment]
The variable generation and pruning functionality are separate processes to prevent race conditions. Just in case your were wondering. It's similar to the way Varnish works with it's ban lurker.

**Comment by GDmac** [comment]
Hmm, that is not what the example states... (emphasis mine)
>  Caching the output of a channel entries tag for 60 minutes. The first time the template is viewed the channel entries tag is run and its output is captured and saved to the database. **On subsequent visits within the following 60 minutes, the output is retrieved from the database** and the channel entries tag does NOT run. **At the end of the 60 minutes the variable expires from the database, and on the next view of the template the cache is regenerated.**

**Comment by croxton** [comment]
**On subsequent visits within the following 60 minutes, the output is retrieved from the database**

That is exactly what happens.

**At the end of the 60 minutes the variable expires from the database, and on the next view of the template the cache is regenerated**
That is a simplification, but the effect is the same. At the end of the 60 minute period the variable will be pruned from the cache. You can configure how quickly the pruning will happen by adjusting the prune probability or setting your cron appropriately. You can ensure pruning happens within microseconds, minutes or hours.

**Comment by GDmac** [comment]
I circumvented the whole issue by modifying the flush_cache method to allow editors to flush the cache
``if ($this->EE->session->userdata['group_id'] > 0  ...``

I understand your concern for race-conditions. I see ways in to set a flock or db lock (you are already using a inodb table which supports row-level locks) but giving editors access to flush_cache is a quick solution. (i might contemplate a special unset() template to limit flushing to certain pages).

**Comment by GDmac** [comment]
@croxton maybe add a link to the cache config page from the caching example to prevent confusing...
