### ISSUE TITLE
config not loaded 

### ISSUE THREAD

**Issue by GDmac** [croxton/Stash#133]
Using EE 2.9.3 I try to set $config['stash_prune_probability'] but it is always 
returning the default of .4 for $this->EE->config->item('stash_prune_probability')

Also ``var_export($this->EE->config);`` does not report any other variable from the stash config file...

**Comment by croxton** [comment]
`$assign_to_config` is the array to use if you're putting it in index.php. Don't go adding to stash/config.php that's for the module use!

**Comment by croxton** [comment]
https://github.com/croxton/Stash/wiki/Installing-%26-upgrading

**Comment by GDmac** [comment]
I'm getting old and rusty ....

**Comment by croxton** [comment]
lol
