### ISSUE TITLE
Offset doesn't affect list_count

### ISSUE THREAD

**Issue by KeironLowe92** [croxton/Stash#135]
I'm not sure whether this is a bug or intended behaviour, but pretty much what the title says. I'd like to get the remaining total after the offset, but it doesn't seem to be affecting the results.

**Comment by croxton** [comment]
That's the correct behaviour for offset. What you're looking for is the 'slice' parameter.

**Comment by KeironLowe92** [comment]
Thanks Mark, although I can't see Slice anywhere in the wiki?

**Comment by KeironLowe92** [comment]
Mark has updated the documentation and slice seems to work for me so closing. Cheers!
