### ISSUE TITLE
Many calls to $ee_uri->_fetch_uri_string();

### ISSUE THREAD

**Issue by leevigraham** [croxton/Stash#140]
It seems stash creates a new EE_URI object for every `exp:stash:get` tag and then fires a couple of methods.

This seems quite expensive. Could the `$uri` be cached?

```
        // fetch the *unadulterated* URI of the current page
        $ee_uri = new EE_URI;

        // documented as a 'private' method, but not actually. Called in CI_Router so unlikely to ever be made private.
        $ee_uri->_fetch_uri_string();
        $ee_uri->_remove_url_suffix();
        $ee_uri->_explode_segments();

        // provide a fallback value for index pages
        $uri = $ee_uri->uri_string();
        $uri = empty($uri) ? $this->EE->stash_model->get_index_key() : $uri;
```

 https://github.com/croxton/Stash/blob/dev/system/expressionengine/third_party/stash/mod.stash.php#L4088

Blackfire.io is showing these calls take up 5% of the page render in a stash heavy site I'm working on.

<img width="539" alt="screen shot 2015-12-08 at 11 31 48 pm" src="https://cloud.githubusercontent.com/assets/25124/11655849/04ce06ec-9e05-11e5-88ef-be747839e72b.png">

<img width="794" alt="screen shot 2015-12-08 at 11 42 16 pm" src="https://cloud.githubusercontent.com/assets/25124/11655892/58f996a0-9e05-11e5-8313-6ee5ad13e261.png">

**Comment by leevigraham** [comment]
The following code adds caching and removes all but one call to `_explode_segments`:

```php
    /**
     * Replace the current context in a variable name
     *
     * @access private
     * @param string    $name The variable name
     * @return string
     */
    private function _parse_context($name)
    {

        $uri = ee()->session->cache('stash', 'uri');

        if(!$uri) {
            // fetch the *unadulterated* URI of the current page
            $ee_uri = new EE_URI;

            // documented as a 'private' method, but not actually. Called in CI_Router so unlikely to ever be made private.
            $ee_uri->_fetch_uri_string();
            $ee_uri->_remove_url_suffix();
            $ee_uri->_explode_segments();

            // provide a fallback value for index pages
            $uri = $ee_uri->uri_string();

            ee()->session->set_cache('stash', 'uri', $uri);
        }

        $uri = empty($uri) ? $this->EE->stash_model->get_index_key() : $uri;
```

<img width="536" alt="screen shot 2015-12-08 at 11 51 14 pm" src="https://cloud.githubusercontent.com/assets/25124/11656060/c460bda0-9e06-11e5-9cac-ceb6029f4783.png">
<img width="621" alt="screen shot 2015-12-08 at 11 51 02 pm" src="https://cloud.githubusercontent.com/assets/25124/11656061/c4648462-9e06-11e5-8c47-cc8a91f77529.png">

**Comment by croxton** [comment]
Nice. But, I'd store the value in `self::$_cache['uri']`rather then Stash's session cache (where stash vars are stored). Want to make a pr against the dev branch?

**Comment by leevigraham** [comment]
+1 Probably should have updated my PR :)
