### ISSUE TITLE
_POST dynamic name in an array

### ISSUE THREAD

**Issue by colinambler** [croxton/Stash#143]
Hey,

I'm trying to retrieve a value from within an array within the POST.  Here's my code:

`{exp:stash:get name="member_primary_address[region]" dynamic="yes"}`

I'm trying to access the region value, but it won't go!   I've tried everything.  Any advice?

<img width="1124" alt="screen shot 2016-04-28 at 6 47 08 pm" src="https://cloud.githubusercontent.com/assets/10900620/14904956/f9eff924-0d71-11e6-840c-7e72b1fa4f28.png">

**Comment by croxton** [comment]
I'm afraid Stash doesn't register POSTed variables that are passed as arrays. You would need individual form fields:
```<input type="text" name="post_code">```

```{exp:stash:get name="post_code" dynamic="yes" match="#^[A-Za-z0-9\s]+$#"}```

**Comment by colinambler** [comment]
Bummer!  No problem though.  I'm on it.  Thanks for the response.
