### ISSUE TITLE
Install stash on EE3

### ISSUE THREAD

**Issue by ashleymarchant** [croxton/Stash#144]
I am unable to install the stash module on EE 3 - stash version 2.6.9. I am putting the stash folder in the system/user/addons but not seeing it show up in the add on manager. 

Please let me know what I might be missing in the installation process. Thanks.

**Comment by croxton** [comment]
Use the EE3 branch https://github.com/croxton/Stash/tree/ee3

**Comment by ashleymarchant** [comment]
Thank you
