### ISSUE TITLE
overwritting stash var while list generation forces new list entry

### ISSUE THREAD

**Issue by thomcheezy** [croxton/Stash#145]
```
{exp:stash:set_list name="dataEntriesHome" parse_tags="yes"}
{exp:channel:entries entry_id="{exp:catme:getEntriesHome}" parse="inward" disable="category_fields|pagination|member_data"}

{stash:url}my default title{/stash:url}
// HERE
{stash:url}{url_title}{/stash:url}

{stash:title}{title}{/stash:title}
{stash:lead}{article_lead}{/stash:lead}

{/exp:channel:entries}
{/exp:stash:set_list}
```

at the word HERE, instead of overwritting the stash variable (if possible?) it creates a new entry in my list. for 5 entries from channel:entries tag, I have finally 10 entries in my stash list. what I am doing wrong, or how can I overwrite vars while generating my stash list.

http://expressionengine.stackexchange.com/questions/9521/stash-how-to-overwrite-a-variable-in-set-list

Stash: 3.0.2
EE: 3.3.3

Best, Thomas

**Comment by croxton** [comment]
Please try using `parse="yes"` rather than `parse_tags="yes"`, since the former will parse conditionals, variables and tags whereas the later only parses tags.

**Comment by thomcheezy** [comment]
thx, done. but still same behaviour.

**Comment by thomcheezy** [comment]
```
<h1>TEST</h1>
{exp:stash:set_list name="test" parse="yes"}
    {exp:channel:entries entry_id="800|803|798|799"}

    {stash:url}default_url{/stash:url}
    {stash:url}{url_title}{/stash:url}<!-- overwrite -->
    {stash:title}{title}{/stash:title}

    {/exp:channel:entries}
{/exp:stash:set_list}

{exp:stash:get_list name="test"}
    TITLE FROM LIST IS: {title}<br>
{/exp:stash:get_list}
```

output screenshot is attached.
![stash_overwrite_output](https://cloud.githubusercontent.com/assets/12068272/17051922/701d3104-4ffb-11e6-910c-c2eb4aa8be21.JPG)

**Comment by croxton** [comment]
You must use a conditional to remove the line you don't want. There can only be one instance of a list variable set.

```
<h1>TEST</h1>
{exp:stash:set_list name="test" parse="yes"}
    {exp:channel:entries entry_id="800|803|798|799"}

        {if cf_my_field == "something"}
            {stash:url}default_url{/stash:url}
        {if:else}
            {stash:url}{url_title}{/stash:url}
        {/if}

        {stash:title}{title}{/stash:title}

    {/exp:channel:entries}
{/exp:stash:set_list}

{exp:stash:get_list name="test"}
    TITLE FROM LIST IS: {title}<br>
{/exp:stash:get_list}
```

**Comment by thomcheezy** [comment]
thx. so the answer here (http://expressionengine.stackexchange.com/a/15029/7044) is wrong and is not possible?

**Comment by croxton** [comment]
No, that simply won't work for a list with multiple rows.

**Comment by thomcheezy** [comment]
thx!
