### ISSUE TITLE
Unable to update Stash embed file DB remains unchanged

### ISSUE THREAD

**Issue by jawwolfe** [croxton/Stash#151]
Hi. When I make a change to a stash embed file, then delete the exp_stash row to allow the cache to update, the changes never appear.  I have made these kind of changes in the past year w/o problem. Using 2.6.7 Thanks.

**Comment by croxton** [comment]
Maybe you didn't delete the right row? Try truncating the table, that will clear all the rows. 

You can use `replace="yes"` on the stash embed tag to have it update automatically (make sure to remove that for production environment).

**Comment by jawwolfe** [comment]
Ok thanks I'll try those ideal.

**Comment by jawwolfe** [comment]
Yea, I had to delete all rows in the table. Thanks!  From now I will clear this cache in that way. In the past I had successfully delete only a single row depending on the file I update.
