### ISSUE TITLE
Stashing a playa field entries matrix

### ISSUE THREAD

**Issue by wesearl91** [croxton/Stash#153]
Is there a way to stash a playa field where there is a matrix field within the entry? Then get it further down, within the same channel entry tags? 

```
{exp:channel:entries}
{playa_field}
    {matrix_field}
        {matrix_value} <-- Somehow stash this value
    {/matrix_field}
{/playa_field}
{/exp:channel:entries}
```
                           	
I've tried everything but I just can't figure it out. Thank you,

**Comment by croxton** [comment]
This can only work if there is only one entry, one playa relationship and one matrix field row. In other words, there is only one instance of `{matrix_value}`:

```
{exp:channel:entries limit="1"}

	{playa_field limit="1"}
	    {matrix_field limit="1"}
	        {exp:stash:set name="my_var"}{matrix_value}{/exp:stash:set}
	    {/matrix_field}
	{/playa_field}

	{exp:stash:get name="my_var" process="end"}

{/exp:channel:entries}
```

**Comment by wesearl91** [comment]
That's great. I only have one row also. Thanks.
