### ISSUE TITLE
EE3: {stash:embed} tag not parsed in embedded template

### ISSUE THREAD

**Issue by outofcontrol** [croxton/Stash#156]
In EE2 it was possible to add `{stash:embed}` tags to templates that were called by other templates, and they would be parsed without trouble. In EE3 this results in the `{stash:embed}` tag simply being passed along unparsed. I have `process="start"` param set.

**Comment by croxton** [comment]
Yes the short syntax will no longer work in EE's own child templates (still works in Stash templates), but you can get this working by prepending with `{exp:`:
```{exp:stash:embed:my_embed}```

**Comment by outofcontrol** [comment]
Strangely enough, this appears to work now in the latest EE with just `{stash:embed}`. Tested by creating 3 templates: test, test2 and test3. Put the {stash:embed} in test, then included test in test2 and test2 in test3 using just normal EE embeds. Page loaded fine. No, process="start" was used.

**Comment by croxton** [comment]
Interesting, thanks!
