### ISSUE TITLE
Stash Entry Page Titles

### ISSUE THREAD

**Issue by soire** [croxton/Stash#158]
Please see my thread [over here](https://expressionengine.stackexchange.com/questions/39538/stash-entry-page-titles/39539#39539). I am trying to print the title of an entry in the <title> tag of a page...getting a random string of numbers like this in the place of the {title} tag (or even in place of plain text).

{71bb8bb2253e73ed74c8484846d80786503398045}

when I attempt to get

{exp:stash:get name="page_title" process="end"}

from

{exp:stash:set_value name="page_title" parse_tags="yes" parse_depth="2" value="{title}" parse="inward"}

Please help?

**Comment by croxton** [comment]
For anyone reading this, the Devot:ee thread is here: 
https://devot-ee.com/add-ons/support/stash/viewthread/16358

I wasn't able to help on this occasion, sadly.
