### ISSUE TITLE
How can I tell if stash is installed?

### ISSUE THREAD

**Issue by jeremydouglas** [croxton/Stash#160]
Hi I'm upgrading a site from EE2 to EE3, trying to get to EE4 eventually.

I followed the Stash installation instructions, but it doesn't look like Stash is installed. Should it show up in the Add-On Manager page in the control panel? I'm not seeing Stash there.

Thanks if anyone can help.

**Comment by croxton** [comment]
Did you download the right branch? You need the ee3 branch.
https://github.com/croxton/Stash/tree/ee3

**Comment by jeremydouglas** [comment]
That's it, thanks!
