### ISSUE TITLE
404 redirection

### ISSUE THREAD

**Issue by anyamiretsky** [croxton/Stash#163]
Hi Mark,
This isn't really an issue, more of a question. How do I make the .htacess Static Page Caching rules work to redirect to our custom 404 page when a nonexisting URL is entered? Ours redirects only to our home page.

**Comment by croxton** [comment]
Also see:
https://github.com/croxton/Stash/wiki/%7Bexp%3Astash%3Anot_found%7D

**Comment by anyamiretsky** [comment]
Thanks for responding Mark. How do I know how PHP is running? I do see CGI/1.1 as the Gateway_Interface in phpinfo? Do I also need to add the new rules described in https://github.com/croxton/Stash/wiki/Static-caching-homepage-in-FastCGI-environments  as well the ? to the index.php rewrite?
I'm fairly new to EE and web development, so I apologize in advance for these questions.

**Comment by croxton** [comment]
Ah yes, you do need to turn that on for 404s to work. No it won't interfere with static caching. 

One important thing - don't static cache the 404 page itself. Some guidelines here which really apply to all sites that use static caching (not just EE):
https://github.com/croxton/Stash/wiki/Caching

The extra block of rewrite rules is only needed if you want to static cache the homepage:
https://github.com/croxton/Stash/wiki/Static-caching-homepage-in-FastCGI-environments

**Comment by anyamiretsky** [comment]
Hi Mark,
Looks like my solution above won't work for me. We have templates that we view directly in our first segment without a template group and this setting will not allow this to happen. So there must be some other way around this since this since our 404's used to work at some point.  I found an interesting schematic  at:

(http://www.jamessmith.co.uk/images/ExpressionEngine_url_schematic.png)

 There is something there which might explain what is happening, but I'm not sure what the option 'is a visible template in default template group' means (second column, fifth one down)? Any ideas?
