### ISSUE TITLE
Parent title association broken — other fields work

### ISSUE THREAD

**Issue by lealea** [croxton/Stash#166]
Hi Mark!

My client is on EE 5.2.3 and Stash 3.0.8. After upgrading them to the latest version of EE, they noticed that some sidebar relationship associations I'd created were not showing the correct URL or entry title.

At first, I thought the entire relationship was broken. However! If I changed the title field to `{parents:entry_id}` instead of the original `{parents:title}` it actually showed the correctly associated entry id, which made sense because the number of entries listed correlated to the number of entries associated. Ditto changing to `{parents:url_title}` with some manual path in front of it instead of `{parents:page_url}`

In order to get over this strangeness, I actually had to use Low Title add-on to pull the proper title using the entry ID to list it properly.

Thoughts?

Lea

**Comment by croxton** [comment]
Hey Lea, EE 5.2.3 had some bugs with the regex parsing of relationship tags which was fixed with the patch referencedin this issue: https://github.com/ExpressionEngine/ExpressionEngine/issues/223

I suspect that patch might address your issue too.

**Comment by lealea** [comment]
Aha, that looks to be it! Thanks!
