### ISSUE TITLE
Disabling caching during development

### ISSUE THREAD

**Issue by roberthallatt** [croxton/Stash#177]
What is the best way to disable caching in a development environment so that I can use a build script?

**Comment by croxton** [comment]
Some options described here: https://devot-ee.com/add-ons/support/stash/viewthread/16293#53433

**Comment by roberthallatt** [comment]
I am using this pattern - [https://github.com/croxton/Stash/wiki/Stash-template-inheritance ](url) but for some reason, no matter what I try, I can't get the cached variables to update while working on the site in development.

**Comment by roberthallatt** [comment]
I have this in my template

`{exp:stash:extend name="block:primaryhero" with="partials:pages:home:hero-option1"}`

And this in my wrapper

`{exp:stash:block:primaryhero}{/exp:stash:block:primaryhero}`

**Comment by croxton** [comment]
I think you can do:
```
{exp:stash:extend name="block:primaryhero" with="partials:pages:home:hero-option1" replace="{global:stash_replace}"}
```
Where `global:stash_replace` is a variable you have set in your environment config ("yes" for local dev).

**Comment by roberthallatt** [comment]
Ok, there was a really silly typo on my part so finally have this working now.
