### ISSUE TITLE
Another PHP 8.1 deprecation notice

### ISSUE THREAD

**Issue by Zignature** [croxton/Stash#178]
I encountered another deprecation notice:
```
Deprecated
htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated
user/addons/stash/mod.stash.php, line 1075

Severity: E_DEPRECATED
```
#### Environment:
Stash v3.1.1
EE 7.2.7
Apache 2.4.54.2
PHP 8.1.13
MariaDB 10.10.2
Windows 11 Pro 22H2 Build 22621.1105

**Comment by croxton** [comment]
Fixed in [#00edcf](https://github.com/croxton/Stash/commit/00edcfdc7e86199e9ee66731c786a16cfd5032ed)
