### ISSUE TITLE
Stash | Mustash: Cache Breaking Rules Not Working

### ISSUE THREAD

**Issue by projectnoontide** [croxton/Stash#180]
Hi, Croxton: (still using your great add-ons)

Cache breaking rules don't appear to work with EE 7.

1. Here's what I'm trying to delete upon an entry update, using the 'after_channel_entry_update' hook:

![stash-mustash-cache-breaking-rules-02](https://user-images.githubusercontent.com/48371903/236356933-ab326a94-a295-409f-9566-715487484eca.png)

2. And here are my rules:

![stash-mustash-cache-breaking-rules-01](https://user-images.githubusercontent.com/48371903/236356987-154835f4-3e3f-40c7-855b-43b52fa906d7.png)

Note: I have tried many variations of the Reg Exp as well, to no avail.

ENV:
- ExpressionEngine, 7.2.17
- PHP Version 8.1.6
- Stash 3.1.1
- Mustash 3.0.1

**Comment by croxton** [comment]
Hey, sorry this is such a late reply, I missed the notification and maybe you worked around this already? I just tested the exact scenario per the screenshot above, with the latest version of EE7 (7.3.14), and it works for me. It's possible the Channel Entries Mustash plugin extension hooks aren't being triggered, so you could try un-checking and re-checking them on the Settings screen of Mustash, so the extension hooks get reinstalled. Or it could be a conflict with other extensions that you have installed (not allowing other plugins to be subsequently triggered).

**Comment by projectnoontide** [comment]
Just realized you commented, and I really appreciate you getting back to me.  Un-checking and re-checking did the job.  Works perfectly now!
